# 第一阶段：安装依赖
FROM node:20-alpine AS deps

# Alpine 用 apk 安装，不是 apt-get！
RUN apk add --no-cache python3 make g

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --omit=dev --force

# 第二阶段：运行
FROM registry.aliyuncs.com/node:20-alpine

WORKDIR /app
ENV NODE_ENV=production

COPY --from=deps /app/node_modules ./node_modules
COPY package.json ./
COPY server ./server

EXPOSE 4000

CMD ["node", "server/adapter/serviceAdapter.js"]